

composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA11" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA12" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA13" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA14" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA15" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.CHA", "pID": "CHA1" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.COA", "pID": "COA1" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.CUSTOMS", "pID": "CUSTOMS1" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.IMMIGRATION", "pID": "IMMIGRATION1" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.LDB", "pID": "LDB1" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.OA1", "pID": "OA11" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.OA2", "pID": "OA21" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.PA", "pID": "PA1" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.PHO", "pID": "PHO1" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.TA", "pID": "TA1" }'
