

composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA11" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA12" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA13" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA14" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA15" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA15" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA15" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA15" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA15" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA15" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA15" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA15" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA15" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA15" }'
composer participant add -c admin@sm -d '{ "$class": "org.hack.sagarmala.VOA", "pID": "VOA15" }'
